config_name : '14_01_2021'
path_to_save : "/home/cyril/PycharmProjects/Starclay/dgs-signalement-ia/clustering_results"
data :
    filename : 'cleaned_data_5.pkl'
    path : "/home/cyril/PycharmProjects/Starclay/dgs-signalement-ia/clustering_results"
    mrv : '/home/cyril/PycharmProjects/Starclay/dgs-signalement-ia/data/declaration_mrv_complet.csv'
topic:
    dictionary:
        used_columns : ['text_lem']
        no_above : 0.8
        no_below : 3
        keep_n : 100000
    corpus :
        
    model :
        name : 'multi-lda'
        num_topic : 150
        passes : 1

cluster:
    model:
        name : "kprototypes"
        add_columns : ['CLASSIFICATION', 'FABRICANT','DCO_ID','TEF_ID','CDY_ID','TDY_ID']
        column_cat_multfactor: 30

        kprototypes:
            n_cluster: 1000
            gamma: 1

        kmeans :
            n_cluster: 1500

        DBSCAN :
            eps: 14
            min_samples: 13.5

        HDBSCAN :
            min_cluster_size: 15
            min_samples : 1
            cluster_selection_epsilon : 0.5
            cluster_selection_method : 'leaf'


        gaussianMixture : 
            n_components: 1500

        bayesianGaussianMixture : 
            n_components: 1500
        agglomerative : 
            n_clusters : 1500
            linkage : 'average' #complete average
            metric : 'jaccard' #'jaccard'
